# Generated by Django 5.0.6 on 2024-06-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('end_time', models.TimeField()),
                ('name', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
                ('floor', models.IntegerField()),
                ('day', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('room', models.IntegerField()),
            ],
        ),
    ]
